version: "3.5"
services:
  maestro:
    image: mysql
    container_name: "maestro"
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - datamaestro:/var/lib/mysql
      - ./maestro.cnf:/etc/my.cnf
      - ./maestro.sql:/docker-entrypoint-initdb.d/maestro.sql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=usuario
      - MYSQL_DATABASE=sicoes
      - MYSQL_PASSWORD=12345

  esclavo1:
    image: mysql
    container_name: "esclavo1"
    restart: unless-stopped
    depends_on:
      - maestro
    ports:
      - 3307:3306
    volumes:
      - dataesclavo1:/var/lib/mysql
      - ./esclavo1.cnf:/etc/my.cnf
      - ./esclavo.sql:/docker-entrypoint-initdb.d/esclavo.sql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=usuario
      - MYSQL_DATABASE=sicoes
      - MYSQL_PASSWORD=12345

  esclavo2:
    image: mysql
    container_name: "esclavo2"
    restart: unless-stopped
    depends_on:
      - maestro
    ports:
      - 3308:3306
    volumes:
      - dataesclavo2:/var/lib/mysql
      - ./esclavo2.cnf:/etc/my.cnf
      - ./esclavo.sql:/docker-entrypoint-initdb.d/esclavo.sql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=usuario
      - MYSQL_DATABASE=sicoes
      - MYSQL_PASSWORD=12345

volumes:
  datamaestro:
  dataesclavo1:
  dataesclavo2:
